services:
  db:
    image: postgres:15
    container_name: odoo-postgres
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    image: odoo:19
    container_name: odoo
    restart: always
    depends_on:
      - db
    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./odoo-data/odoo-addons:/mnt/extra-addons
      - ./odoo-data/config:/etc/odoo
      - ./odoo-data/filestore:/var/lib/odoo/.local/share/filestore
    networks:
      - odoo-network
    ports:
      - "8069:8069"
    command: >
      odoo --database=odoo
             --db-filter=^.*$
             --addons-path=/mnt/extra-addons
             --data-dir=/var/lib/odoo
             --log-level=info

  redis:
    image: redis:7
    container_name: odoo-redis
    restart: always
    networks:
      - odoo-network

volumes:
  odoo-db-data:

networks:
  odoo-network:
    driver: bridge
